### ISSUE TITLE
Proposal: complete integration (cli) tests

### ISSUE THREAD

**Issue by vdemeester** [docker/libcompose#10]
It would be cool to cover the project with some integration cli to be more confident on the contributions we all do :sweat_smile:. What do you think ?

This would mean :
- [X] Define a general (and simple to start) structure to write tests and execute them (taking inspiration of other docker projects). This is actually already done :sweat_smile:, didn't look as much as I should have :blush:.
- [X] Not running integration tests when running tests — or separate the run of unit-tests and integration-tests and have tests run both. (right now, running tests runs ``integration``)
- [X] Use docker to run the integration tests (just like on the docker engine project). It feels strange to use docker to run tests, but not the integration tests. Maybe the unit-tests too :sweat_smile:.
- [X] Create an *goal* in the ``Makefile`` (to do ``make test-integration-cli``)

PS : I'm more than willing to help on that and sends PRs, but made the issue to get your thought on this and to keep track of the work that would be done on the subject.

**Comment by ibuildthecloud** [comment]
100% agree on all points.  I'll be working on getting CI setup tomorrow too.

As a general goal the integration test should be able to run against libcompose and the python docker-compose.  This can help establish confidence that we conform with docker-compose where we want to.

**Comment by aanand** [comment]
Agreed.

**Comment by vdemeester** [comment]
Another question, how do you feel about the way the ``docker/docker`` is done — what do I mean is, any ``make`` *goals* starts up the docker image (and build it if needed) and run the scripts in the container. I personally love it (because there is a few thing I don't need to setup on my host :blush:).

Asking this because depending on the answer, the PRs depends. @ibuildthecloud feel free to ping me on irc (same username) when you work on it so I can help :wink: (I'm in France though so the *up* time shared might be.. small :sweat: ).

**Comment by cpuguy83** [comment]
Could totally use bats to do this too

**Comment by ibuildthecloud** [comment]
I don't know if I'm personally a fan of bats.  I'd rather just stick to Go if possible.  I feel like all test frameworks you grow to hate, so might as we stick with Go as the barrier to entry is small.  Also with the integration tests we have already it's basically run `docker-compose` and then use the API client to assert all the right things happened.  So sticking with a programming language seems better in my opinion.

@vdemeester I like the Docker approach very much.  I'm up for rewriting any of the build script.  I'd really like the integration test suite to be run in Docker in Docker.

**Comment by dnephin** [comment]
>  I feel like all test frameworks you grow to hate,

I think http://pytest.org/ broke that role for me. It's pretty great.

-----

If this library is supposed to share any feature set with `docker-compose` (my understanding is that is the idea), I think it would be good to have an acceptance test suite that is language agnostic, so a single suite can be run against both packages.

Each can still have their own tests to verify internal implementation details, but the acceptance test suite asserts that the high level features/api are actually compatible.

**Comment by ibuildthecloud** [comment]
@dnephin I actually agree, I love py.test and we use it a lot at Rancher.  I thought of using that though I really feel it's a bit better to just stick with Go.  It falls in line with the rest of the Docker Project.

The intention of the integration test suite is that it will fork/exec the binary and run tests that way.  So the language of the test framework shouldn't impact the ability of the suite to run against both projects.

**Comment by vdemeester** [comment]
I think this one can be closed for now, am I right ? :sweat_smile:
