### ISSUE TITLE
Libcompose with Docker-Machine - x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by gondor** [docker/libcompose#119]
Now that libcompose is `go gettable` (thank you)  I proceeded to finish incorporating it in my current project.  During a basic project up test the following error is occurring.   I've also tried simplified test code in a new project to reproduce.

I wasn't seen this issue prior to libcompose being `go gettable`.  Not sure if it's related

### Error Log
```
INFO[0000] Project [my-compose]: Starting project
INFO[0000] [0/5] [search]: Starting
ERRO[0000] Failed Starting search : Get https://192.168.99.100:2376/v1.20/version: x509: certificate signed by unknown authority
```

### Test Code
Using the example as is from the README and any existing docker-compose.yml in the same directory:
```
package main

import (
    "log"

    "github.com/docker/libcompose/docker"
    "github.com/docker/libcompose/project"
)

func main() {
    project, err := docker.NewProject(&docker.Context{
        Context: project.Context{
            ComposeFile: "docker-compose.yml",
            ProjectName: "my-compose",
        },
    })

    if err != nil {
        log.Fatal(err)
    }

    project.Up()
}
```

**Comment by vdemeester** [comment]
@gondor how are you pointing to the machine ?

**Comment by gondor** [comment]
I was testing it like docker-compose where it picks up the env variables.  Does libcompose require setting the machine via code?  I don't mind either way

Env vars
```
DOCKER_HOST=tcp://192.168.99.100:2376
DOCKER_MACHINE_NAME=default
DOCKER_TLS_VERIFY=1
```

**Comment by vdemeester** [comment]
@gondor does your `docker-machine` version not setting `DOCKER_CERT_PATH` ? (I have to try though)

**Comment by gondor** [comment]
@vdemeester I apologize I should of done a `env | grep DOCKER` .  Yes it is setting the cert path.  Heres all DOCKER env vars on OS X 10.11

```
DOCKER_HOST=tcp://192.168.99.100:2376
DOCKER_MACHINE_NAME=default
DOCKER_TLS_VERIFY=1
DOCKER_CERT_PATH=/Users/junruh/.docker/machine/machines/default
```

**Comment by vdemeester** [comment]
@gondor This can be splitted into two points and one problem. At first I thought you were using the `libcompose-cli` bin and it works.

But if you use `libcompose` as a lib, you need to handle the `DOCKER_TLS_VERIFY` environment variables for now (neither `libcompose` or the docker-client lib we use does automatically handle it).

For example, the following code would work (it's ugly and can be written way better though :sweat_smile:) :

```go
package main

import (
	"log"
	"os"

	"github.com/docker/libcompose/docker"
	"github.com/docker/libcompose/project"
)

func main() {
	clientFactory, err := docker.NewDefaultClientFactory(docker.ClientOpts{})
	if err != nil {
		log.Fatal(err)
	}

	tlsVerify := os.Getenv("DOCKER_TLS_VERIFY")

	if tlsVerify == "1" {
		clientFactory, err = docker.NewDefaultClientFactory(docker.ClientOpts{
			TLS:       true,
			TLSVerify: true,
		})
		if err != nil {
			log.Fatal(err)
		}
	}

	project, err := docker.NewProject(&docker.Context{
		Context: project.Context{
			ComposeFile: "docker-compose.yml",
			ProjectName: "yeah-compose",
		},
		ClientFactory: clientFactory,
	})

	if err != nil {
		log.Fatal(err)
	}

	project.Up()
}
```

**Comment by gondor** [comment]
That worked like a champ! Thank you very much @vdemeester
