### ISSUE TITLE
Go Get fails for docker/pkg/nat

### ISSUE THREAD

**Issue by mlhoque** [docker/libcompose#137]
docker/docker/pkg/nat was replaced by docker/go-connections/nat.

**Comment by vdemeester** [comment]
@mlhoque thanks for the report. I'm working on it in my [bum-docker-1.10](https://github.com/vdemeester/libcompose/tree/bump-docker-1.10) branch, but that is why we are using vendoring (`GO15VENDOREXPERIMENT`) :stuck_out_tongue_closed_eyes:.

**Comment by mlhoque** [comment]
@vdemeester Thank you for the update!
