### ISSUE TITLE
Proposal : Enable `golint` on the code base

### ISSUE THREAD

**Issue by vdemeester** [docker/libcompose#14]
Taking the description directly from docker#14756.

> We want to enable golint on our codebase for several reasons:
> 
> - We want to improve code quality
> - We need objective filters on quality to help us discriminate bad pull requests

There is some work to do, but I think it's would be better to do it as *early* as possible (easier to do). And as libcompose is intended to be used as a library more than just a cli, documentation and quality is import I think.

WDYT about that ?
If you think we should do it, we'll keep track of the work on this issue then :wink:.

Package (and linting status) :
- [X] cli/app #31
- [X] cli/command #31
- [X] cli/docker/app #31
- [X] cli/logger #31
- [X] cli/main
- [X] docker #51 
- [X] logger #50 
- [X] lookup
- [X] project #49 
- [X] utils #37
- [X] version

**Comment by dave-tucker** [comment]
:+1: we should probably `go vet` too
http://goreportcard.com/report/docker/libcompose

**Comment by ibuildthecloud** [comment]
Both would be awesome.  Always better now than later.  @dave-tucker I had no idea that goreportcard site existed.  That is cool.

**Comment by vdemeester** [comment]
@dave-tucker yeah me neither, pretty cool site :blush:. I'll setup the golint and govet validation the way there setup in docker and we'll have then have time to cover package as we go then :wink:.

**Comment by gdevillele** [comment]
goreportcard looks awesome! :+1: 
Thank you.
