### ISSUE TITLE
Support version 2 of compose file

### ISSUE THREAD

**Issue by runseb** [docker/libcompose#147]
Hi, I don't think lib compose can currently parse version 2 compose files.

**Comment by vdemeester** [comment]
@runseb true, it's on the roadmap for `v0.2.0` : https://github.com/docker/libcompose/wiki/0.2.0-Milestone-Project-Page :wink:

**Comment by ngtuna** [comment]
Hi @vdemeester , is there any progress on this item ? I'm working on it as well. Considering to add a new `ServiceConfigV2` struct for compose file v2 like this. https://gist.github.com/ngtuna/c84d59b497bca62e2e9f

But I found it's not really convenience to maintain two structs of v1 and v2. How's your thought ?

**Comment by vdemeester** [comment]
@ngtuna I'm working on this yeah, but no "public" progress right now :smile:. I'll ping you for early reviews :)

**Comment by F21** [comment]
@vdemeester Thank you so much for working on this! Is there any timeline for when this might surface? :smile:

**Comment by vdemeester** [comment]
@F21 I'm hoping at the end of this week :wink:

**Comment by kolis** [comment]
+1 This is a major issue imo

**Comment by mkamlesh** [comment]
Hello, are there plans to resolve this issue in very near future?

**Comment by vdemeester** [comment]
@mkamlesh yes @joshwget (and I) is working on it :wink:. Should definitely land for 0.3.0.

**Comment by mkamlesh** [comment]
Thanks @vdemeester !! What's the estimated date for 0.3.0 release?

**Comment by vdemeester** [comment]
Should be somewhere in June

**Comment by mkamlesh** [comment]
Great. Thanks!

**Comment by shouze** [comment]
@vdemeester Hi, looks to be done on [your libcompose fork master branch](https://github.com/vdemeester/libcompose), that's it? How could I help you with @joshwget to make things move forward?

I would love to use asap an upgraded version of libcompose to run v2 compatible services within rancher for example thus closing https://github.com/rancher/rancher/issues/3973

**Comment by vdemeester** [comment]
@shouze it's already in current master (parsing and populating the internal struct), but there is still some bugs and stuff that are not supported (like networks and volumes) for now.

**Comment by shouze** [comment]
@vdemeester how can I help on either network and volumes? If you open some issues, this way I could take on it.

**Comment by vdemeester** [comment]
@shouze good idea, I'll open one issue for volumes, on for networks. I was going to take networks one first so feel free to work on the volume part :wink:

**Comment by vdemeester** [comment]
The parsing should be almost OK. What is missing still: 
- Validation as we do on v1 (using schema)
- Networks & Volumes management, PRs to come from me and @shouze

**Comment by shouze** [comment]
@vdemeester I'm a bit late for Volumes but no worry I don't give up ;)

**Comment by vdemeester** [comment]
Once #339 is merged, v2 will be support (in 0.3.0, so in less than a week :wink:)
