### ISSUE TITLE
Revamp cli with spf13/cobra

### ISSUE THREAD

**Issue by vdemeester** [docker/libcompose#155]
Switch to [spf13/cobra](https://github.com/spf13/cobra) for the CLI and make it more `docker-compose` like.
- docker-compose

``` bash
$ docker-compose up -d
Creating toto_simple_1
Creating toto_another_1
 $ docker-compose stop
Stopping toto_another_1 ... done
Stopping toto_simple_1 ... done
 $ docker-compose rm -f 
Going to remove toto_another_1, toto_simple_1
Removing toto_another_1 ... done
Removing toto_simple_1 ... done
```
- libcompose

``` bash
libcompose-cli up -d
WARN[0000] Note: This is an experimental alternate implementation of the Compose CLI (https://github.com/docker/compose) 
INFO[0000] Project [toto]: Starting project             
INFO[0000] [0/2] [simple]: Starting                     
INFO[0000] [0/2] [another]: Starting                    
INFO[0000] [1/2] [simple]: Started                      
INFO[0000] [2/2] [another]: Started 
$ libcompose-cli stop
WARN[0000] Note: This is an experimental alternate implementation of the Compose CLI (https://github.com/docker/compose) 
INFO[0000] Project [toto]: Stopping project             
INFO[0000] [0/2] [simple]: Stopping                     
INFO[0000] [0/2] [another]: Stopping                    
INFO[0000] [0/2] [another]: Stopped                     
INFO[0000] [0/2] [simple]: Stopped                      
INFO[0000] Project [toto]: Project stopped 
$ ibcompose-cli rm -f
WARN[0000] Note: This is an experimental alternate implementation of the Compose CLI (https://github.com/docker/compose) 
INFO[0000] [0/2] [simple]: Deleting                     
INFO[0000] [0/2] [another]: Deleting                    
INFO[0000] [0/2] [simple]: Deleted                      
INFO[0000] [0/2] [another]: Deleted                     
INFO[0000] Project [toto]: Deleting project             
INFO[0000] [0/2] [simple]: Deleting                     
INFO[0000] [0/2] [another]: Deleting                    
INFO[0000] [0/2] [simple]: Deleted                      
INFO[0000] [0/2] [another]: Deleted                     
INFO[0000] Project [toto]: Project deleted
```

**Comment by kunalkushwaha** [comment]
Hi @vdemeester have you started working on this? If not, can I give a try?
I have  implemented  kind of ``libcompose-cli config`` with ``spf13/cobra``, but waiting for this PR.

**Comment by vdemeester** [comment]
hey @kunalkushwaha, I'm back from vacation, sorry for the delay.
I did not start on working on this yet, so feel free to make a PR on it if you have time to work on it :wink: :+1:. Thanks !

**Comment by kunalkushwaha** [comment]
Since same flag for command and subcommand is not supported by spf13/Cobra framework https://github.com/docker/libcompose/pull/198#discussion-diff-60447601L24 , Should we concentrate on making cli outputs  similar to docker-compose?

Meanwhile, will look for solution in cobra for same.

**Comment by joshwget** [comment]
@kunalkushwaha Any updates on finding a solution? The more I look at moving to Cobra the more I like the idea.

**Comment by vdemeester** [comment]
@joshwget did not look at it, I'm moving this to 0.4.0 milestone and I'll take a look at the `-f` problem :stuck_out_tongue_closed_eyes:

**Comment by kunalkushwaha** [comment]
Sorry for late update. It will require a patch in spf13/cobra.

**Comment by vdemeester** [comment]
@kunalkushwaha can you take a look at https://github.com/dnephin/cobra/ maybe :angel: (used for `docker/docker`)

**Comment by kunalkushwaha** [comment]
Thanks, Will look into it  :)

**Comment by kunalkushwaha** [comment]
@vdemeester I think docker/docker have similar issue https://github.com/docker/docker/blob/506234e3f0f6d8f8a0629e09f38dfe96ada025c2/api/client/container/create.go#L53

**Comment by vdemeester** [comment]
Hum, that suck a little bit :sweat: I'm not sure what to do here, other than trying to see if we can fix this into `spf13/cobra` library :angel:
