### ISSUE TITLE
Support loggerfactory for building images

### ISSUE THREAD

**Issue by bfosberry** [docker/libcompose#159]
I'd rather not capture and lock stdout :P so what would work better for me is to support logger factories for creating loggers for capturing build output for specific services or images. I'd like some guidance on how this would integrate well. My initial thoughts are to tie into a new BuildLoggerFactory specifically, for https://github.com/docker/libcompose/blob/master/docker/builder.go#L60, and default it to a stdout logger sto preserve backwards compatibility. 

thoughts?

**Comment by vdemeester** [comment]
@bfosberry yeah, I used `os.Stdout` for weird backwards compatibility but I should have had a FIXME there to say "find a clever way to log that". So yeah, sounds good to me :wink:

**Comment by bfosberry** [comment]
Cool! I'll need to find a way to trim out all stdout printing and override internal loggers

**Comment by vdemeester** [comment]
I think this one is fixed now (https://github.com/docker/libcompose/pull/163)
