### ISSUE TITLE
How do I set the docker host when using libcompose?

### ISSUE THREAD

**Issue by F21** [docker/libcompose#166]
I am following the example in `README.md`:
```go
func main() {
    project, err := docker.NewProject(&docker.Context{
        Context: project.Context{
            ComposeFiles: []string{"docker-compose.yml"},
            ProjectName:  "my-compose",
        },
    })

    if err != nil {
        log.Fatal(err)
    }

    project.Up()
}
```

I tried creating my own `EnvironmentLookup`:

```go
type EnvLookup struct {
	endpoint string
}

func (c EnvLookup) Lookup(key, serviceName string, config *project.ServiceConfig) []string {
	if key == "DOCKER_HOST" {
		return []string{fmt.Sprintf("%s=%s", "DOCKER_HOST", "tcp://192.168.1.100:2375")}
	}

	return []string{}
}


func main() {
    project, err := docker.NewProject(&docker.Context{
        Context: project.Context{
            ComposeFiles: []string{"docker-compose.yml"},
            ProjectName:  "my-compose",
            EnvironmentLookup: EnvLookup{},
        },
    })

    if err != nil {
        log.Fatal(err)
    }

    project.Up()
}
```

However, `EnvLookup` is never called. What's the correct way to set the docker host (within my go code, rather than using the `DOCKER_HOST` environment variable)?

**Comment by F21** [comment]
The trick is to set the client factory:

```go
clientFactory, _ := docker.NewDefaultClientFactory(docker.ClientOpts{Host: endpoint}) //error checking omitted for brevity

project, err := docker.NewProject(&docker.Context{
        Context: project.Context{
            ComposeFiles: []string{"docker-compose.yml"},
            ProjectName:  "my-compose",
            EnvironmentLookup: EnvLookup{},
        },
       ClientFactory: clientFactory,
 })

```

**Comment by vdemeester** [comment]
@F21 yes :+1: 
We will need way more documentation at some point :stuck_out_tongue:

**Comment by deviantony** [comment]
@vdemeester Am I correct to say that `docker.NewDefaultClientFactory()` is not the correct method to create a ClientFactory anymore? I'm trying to pass TLS options to the `client.NewDefaultFactory()` but I've got conflict issues with the `github.com/docker/docker/pkg/tlsconfig` package and the one vendored in the libcompose library.

**Comment by vdemeester** [comment]
@deviantony the conflict you have is probably due to go vendoring and the weird ways it is not working with nested vendoring (i.e. if you use libcompose and vendor it, you need to remove the `vendor` folder from it).

**Comment by deviantony** [comment]
Actually, I'm using the following:

```
clientFactory, err := client.NewDefaultFactory(client.Options{
		TLS:        true,
		TLSVerify:  true,
		Host:       "tcp://docker.domain:2375",
		TLSOptions: tlsconfig.Options{
			CAFile:             "/path/to/ca.pem",
			CertFile:           "/path/to/cert.pem",
			KeyFile:            "/path/to/key.pem",
			InsecureSkipVerify: false,
		},
	})
```

And got the following issue:

```
cannot use tlsOptions (type "github.com/docker/docker/pkg/tlsconfig".Options) as type "github.com/docker/libcompose/vendor/github.com/docker/go-connections/tlsconfig".Options in field value
```

I'm not vendoring libcompose at all. Is this the correct way to create a ClientFactory?

**Comment by vdemeester** [comment]
@deviantony yes I think it is the right way to create `ClientFactory`. The problem is the `vendor` folder of `libcompose` then. Basically, you have a `github.com/docker/docker/pkg/tlsconfig` version in your `GOPATH` and there is one in the `vendor` folder of `libcompose`, making the go compiler scream 😓 

This is the weird state of `go` vendoring  for now.. If you remove the `vendor` folder of `libcompose`, it should work (given the dependency you have still satisfy libcompose)..

**Comment by deviantony** [comment]
Right, looks like an ugly workaround to me :-)

Do you know any other way to have libcompose connect to a remote TLS Docker host?

**Comment by anggahusni27** [comment]
Is there any update or workaround about this issue?
