### ISSUE TITLE
Is project.Up() synchronous?

### ISSUE THREAD

**Issue by F21** [docker/libcompose#171]
I am running `project.Up()`, and then after that, using the `engine-api` package to query the daemon to see which containers have exited and failed.

I am seeing some asynchronous looking behaviour:

For example: Sometimes, it returns an empty array (maybe the containers were not yet started before `client.ContainerList()` ran?

Sometimes, I get 1 container (but there should be 2).

If `project.Up()` is indeed asynchronous, is there a channel to wait on it for it to complete?

**Comment by F21** [comment]
I am suspecting this is the case because if I add `time.Sleep(5 * time.Second)` before the `engine-api` call, it works correctly.

**Comment by kunalkushwaha** [comment]
Yes it it async. You need to wait for event [project.EventContainerStarted] (https://github.com/docker/libcompose/blob/96f52273d4132d80502409e5431ce44b14172913/project/types.go#L13)


https://github.com/docker/libcompose/blob/master/docker/container.go#L277

The calling function stack is as below for Up()

c.Up(imageName string) : [container.go#L251](https://github.com/docker/libcompose/blob/master/docker/container.go#L251)
s.up(imageName string, create bool) : [service.go#L187](https://github.com/docker/libcompose/blob/master/docker/service.go#L187)
s.Up() : [service.go#L187](https://github.com/docker/libcompose/blob/master/docker/service.go#L187)

Hope it helps.

**Comment by kunalkushwaha** [comment]
You may want to look for adding listener for your project with [AddListener](https://github.com/docker/libcompose/blob/18211431fd3c9fc49deb0e4937832191ec5b4f5b/project/project.go#L447)

**Comment by F21** [comment]
I just did some experimenting with adding a listener to listen for `EventContainerStarted`, however, I am still seeing the same issues. I think this is because the docker daemon will start the container and return immediately rather than wait for the container to start and execute before returning.

I think the best way forward would be to poll for the container in the project (by matching the project label) and go from there.

Another disadvantage of listening to `EventContainerStarted` is that it is obviously not fired for containers that are already running, so I would still need to make a call to the daemon to check for running containers.

**Comment by kunalkushwaha** [comment]
Docker Create/Start/Restart API's can only ensure, if Container is created successfully or not.
But if application within it start asynchronously, Application may fail later.

BTW, Docker Events is also one of the way, you may use.

**Comment by kunalkushwaha** [comment]
Docker events are not yet available in libcompose. Though it is in roadmap. https://github.com/docker/libcompose/issues/124

**Comment by F21** [comment]
Thanks for linking me to that issue. I ended up using polling with a timeout, so that should work pretty well for now, until I can switch over to docker events.
