### ISSUE TITLE
A package for interpolation

### ISSUE THREAD

**Issue by vdemeester** [docker/libcompose#182]
> It is quite useful to parse a text file in the same exact way that
> compose does. One can imagine this being useful for GUI applications or
> custom parsers.

The idea is to extract the `Interpolate` function in a generic way, usable from outside libcompose.

**Comment by joshwget** [comment]
Do we still want a separate package for interpolation after the project/config split? If we do decide to move interpolation out of the config package, I think it would also make sense to move validation into its own package.
