### ISSUE TITLE
cannot unmarshal object into Go value of type []string 

### ISSUE THREAD

**Issue by jainvipin** [docker/libcompose#195]
I must be missing something basic here. The latest libcompose (top of the tree with following commit tag):

```
commit b0878191358b07413c5fde9b1e865e1a2fa81f38
Merge: 636c1ec 3759c8d
Author: Vincent Demeester <vincent@sbr.pm>
Date:   Fri Apr 8 11:25:39 2016 +0200

    Merge pull request #190 from joshwget/split-project-package
    
    Split project package into project, config, and yaml packages

```

When I use the following docker-compose.yml (picked from one of the issue that was discussed earlier):

```
/opt/gopath/src/github.com/docker/libcompose$ cat docker-compose.yml 
hello:
  image: busybox
  stdin_open: true
  tty: true
```

Using docker version 1.9.0
```
/opt/gopath/src/github.com/docker/libcompose$ docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:48:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:48:04 UTC 2015
 OS/Arch:      linux/amd64
```

With a libcompose build as above, if a composition is started results into the error:
```
/opt/gopath/src/github.com/docker/libcompose$ bundles/libcompose-cli -p test up -d 
WARN[0000] Note: This is an experimental alternate implementation of the Compose CLI (https://github.com/docker/compose) 
INFO[0000] Project [test]: Starting project             
INFO[0000] [0/1] [hello]: Starting                      
ERRO[0000] Failed Starting hello : Error response from daemon: json: cannot unmarshal object into Go value of type []string 
ERRO[0000] Failed to start: hello : Error response from daemon: json: cannot unmarshal object into Go value of type []string 
FATA[0000] Error response from daemon: json: cannot unmarshal object into Go value of type []string 
```

DOCKER_API_VERSION is not set, however even if I set it to v1.21 it results into the same behavior.

It used to work just fine. Am I missing something?

**Comment by jainvipin** [comment]
Ref #146

**Comment by yangyuqian** [comment]
Hi,

I compiled the latest libcompose on master branch, and here is head of the git log:
![image](https://cloud.githubusercontent.com/assets/7478577/14415569/53108d40-ffd3-11e5-8d5d-1435583b9d7b.png)

I run "export DOCKER_API_VERSION=1.21" before executing the libcompose-cli and it's still not working:
![image](https://cloud.githubusercontent.com/assets/7478577/14415592/7b976fa4-ffd3-11e5-8cf6-2e65fad63ad8.png)

I'm using Docker 1.9.1:
![image](https://cloud.githubusercontent.com/assets/7478577/14415613/9b2b308a-ffd3-11e5-80ea-6b1b3a43b184.png)

Did i miss anything here?

**Comment by jainvipin** [comment]
@yangyuqian - seems like you are running into the same issue; may be top of the tree is broken.
It root cause may be similar to what is mentioned in https://github.com/docker-php/docker-php/issues/122 which is due to empty object vs. empty array. I will look more into it tomorrow.

**Comment by vdemeester** [comment]
@jainvipin @yangyuqian Definitely reproductible, thanks. (It confortes me to enable some sort of *multiple-daemon* testing on the CI).

**Comment by vdemeester** [comment]
Yes, definitely fixed use the master on `engine-api`. Bumping the version :wink:

**Comment by yangyuqian** [comment]
@vdemeester Thanks, I'll do more test tomorrow.

btw, the engine-api works correctly with the same daemon(mentioned above, tested with the example in https://github.com/docker/engine-api)

**Comment by vdemeester** [comment]
@yangyuqian yep, that's why I've update the engine-api vendored in here.. it fixes it :wink:

**Comment by yangyuqian** [comment]
@vdemeester Thanks, it works now ^_^

**Comment by jainvipin** [comment]
+1 @vdemeester - tried out the latest, works like a charm
Let me know if I can help adding some testing for 1.9 docker daemon...
