### ISSUE TITLE
Complete logs command

### ISSUE THREAD

**Issue by vdemeester** [docker/libcompose#210]
Add support for more flags/options for the `logs` command, and set the same behaviour as the compose one :

> - Added --follow, --timestamp, and --tail flags to the
>   docker-compose logs command.
> - docker-compose logs now shows logs for new containers that are created
>   after it starts.
> - docker-compose logs no longer follows log output by default. It now
>   matches the behaviour of docker logs and exits after the current logs
>   are printed. Use -f to get the old default behaviour.

**Comment by vdemeester** [comment]
This should be fixed at some point with the related PR: https://github.com/docker/libcompose/pull/290

**Comment by JayHaoDing** [comment]
@vdemeester #290 and https://github.com/docker/engine-api/pull/315 were both closed. Could you please comment if `tail` option can be supported in libcompose? Thanks.

**Comment by vdemeester** [comment]
@JayHaoDing yes at some point it will, I just have to find time to work on that again :angel:
