### ISSUE TITLE
COMPOSE_FILE environment variable can contains multiple files

### ISSUE THREAD

**Issue by vdemeester** [docker/libcompose#212]
> The COMPOSE_FILE environment variable can now contain multiple files,
separated by the host system's standard path separator (: on Mac/Linux,
; on Windows).

Right now, I think `libcompose` assumes the `COMPOSE_FILE` environment file is only refering to one file… We should support the same as `docker-compose` does :angel:

**Comment by dustinrc** [comment]
I have a commit ready dustinrc/libcompose@16a53f551f6945e847453f6fb2b93f2c912a2546, but there is a side effect that may be undesired (explained in the commit message). Only now did I notice that this project [wants to move to cobra](155) (and viper?), which may handle this problem better. Hold off on this issue or is my change ok to move forward with for now?
