### ISSUE TITLE
Different app image names between docker-compose and libcompose

### ISSUE THREAD

**Issue by jamespacileo** [docker/libcompose#228]
Hi just stumbled on this one.

For a project in a folder such as "example-app" with an app called "app", 

docker-compose names the image `exampleapp_app`, 
while libcompose names the image `example-app_app`.

I want to thank you for libcompose as it's the only way to get interactive mode working on Windows! 

If this change gets in then I can magically start using libcompose with Docker Native for Windows :smile:

**Comment by vdemeester** [comment]
@jamespacileo Hi :) Thanks for the report. I noticed that (along with the name in the logs), working on a quick fix :wink:. 

Added to the 0.3.0 milestone :wink:

**Comment by jamespacileo** [comment]
👍 thank you! :)
