### ISSUE TITLE
How do I get console messages as the containers start?

### ISSUE THREAD

**Issue by rajeevb2** [docker/libcompose#271]
With docker-compose up, you get all the log messages from each of the containers started.

With libcompose (up), I only get 1 line that the container was started.

How do I get these log messages. Here is the snippet of the code that implements Up

        project, err := docker.NewProject(&docker.Context{
                Context: project.Context{
                   ComposeFiles: []string{fileName},
                   ProjectName:  hostName,
                },
        })

        if err != nil {
                log.Fatal(err)
        }
        project.Up(options.Up{})

**Comment by vdemeester** [comment]
Hi @rajeevb2,

as libcompose is a library some commands are a little bit different that the *command-line* counter part. And this is the case for `Up`. 

`project.Up` will do all the things `docker-compose up` does but will not print logs by default. To do so, you need to call `project.Log`. You can look how it is done for the *command-line* here for inspiration: https://github.com/docker/libcompose/blob/master/cli/app/app.go#L129.

**Comment by rajeevb2** [comment]
Thanks @vdemeester,

I tried adding
        project.Log(true, c.Args()...)
after the up, but it does not display the logs created when the **instances are created**. 

I did look at the cli for inspiration and could not figure out how to enable this.

**Comment by joshwget** [comment]
I'm actually having the same issue. Calling `Up` followed by `Log` isn't exactly the same as logging as each container is started. libcompose used to behave the latter way, but as of [this commit](https://github.com/docker/libcompose/commit/426597a6f5286c42b266334f0576970b8b569451) it behaves the former way. I think there are use cases for both of these, so this should probably be configurable in some way.

**Comment by vdemeester** [comment]
Hum.. It feels a little weird (I'm not sure what is different) but I think I might know as logs is not yet "dynamic" as in compose..

Ideally (and in the near future) we could call p.Log before p.Up or anything and it should log anything happening..

**Comment by rajeevb2** [comment]
@joshwget 
I manually undid the changes related to Log in context.go and containers.go and it still didn't print the log messages on stdout. Is there something else to setup?

@vdemeester 
Enabling "create" logging is very important. I had to run docker-compose to get the logs. I would rather use libcompose.

**Comment by vdemeester** [comment]
@rajeevb2 by "create" logging you mean have the logs "live" while it is been creating ? if yes, then this should be fix in 0.3.0 with some refactoring on the `Log` methods and events 😉

**Comment by rajeevb2** [comment]
@vdemeester. Thanks. Do you know when this would be fixed? I am happy to test this.

**Comment by rajeevb2** [comment]
@vdemeester. I was able to get logs to work. I did not initialize loggerFactory in Context. Once I did that it worked.
