### ISSUE TITLE
Composefile v2: support volumes

### ISSUE THREAD

**Issue by vdemeester** [docker/libcompose#277]
Add support for managing volumes for v2 services (meaning for projects that have `VolumeConfig` populated).

**Comment by shouze** [comment]
Thank you, I'm new to the project so maybe I'll have some questions of course. I've cloned the project & digging into it ATM.

**Comment by vdemeester** [comment]
@shouze no problem :wink: If you're on IRC, feel free to ping me :wink:

**Comment by joshwget** [comment]
@shouze @vdemeester Have either of you started any work on this yet? I'd like to add this feature soon and I'm not sure if I'll be starting from scratch or not :smile:

**Comment by vdemeester** [comment]
@shouze started to work on it :angel:

**Comment by shouze** [comment]
@vdemeester ok, I can push the few code I've already produced you can cherry pick any commit if you want: https://github.com/shouze/libcompose/compare/master...277-support-volumes.

**Comment by joshwget** [comment]
@shouze Is what you have in a complete enough state that it could be put in master? If that's the case maybe we can just get that in and iterate from there.

If not, would you mind if I cherry-pick your commit and finish off the remaining work?

**Comment by shouze** [comment]
@joshwget not complete enough, would prefer a cherry-pick. Also you probably may have to make 2 PR:
- The first one with the last commit I've pushed to expose yaml volume config like @vdemeester have done with network's one in https://github.com/docker/libcompose/pull/292.
- The second one with volume support implemented.
