### ISSUE TITLE
libcompose-cli not working with docker-beta.

### ISSUE THREAD

**Issue by kunalkushwaha** [docker/libcompose#279]
docker-compose works fine but libcompose-cli could't connect to docker daemon.
Is there any environment variable need to be set?

```
WARN[0000] Note: This is an experimental alternate implementation of the Compose CLI (https://github.com/docker/compose)
INFO[0000] [0/2] [redis]: Starting
ERRO[0000] Failed Starting redis : Cannot connect to the Docker daemon. Is the docker daemon running on this host?
ERRO[0000] Failed to start: redis : Cannot connect to the Docker daemon. Is the docker daemon running on this host?
INFO[0000] [0/2] [web]: Starting
ERRO[0000] Failed Starting web : Cannot connect to the Docker daemon. Is the docker daemon running on this host?
ERRO[0000] Failed to start: web : Cannot connect to the Docker daemon. Is the docker daemon running on this host?
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Comment by kunalkushwaha** [comment]
The TLS certificate path need to be set. Any idea, where are TLS certs for docker-beta ?

**Comment by nickschuch** [comment]
Did you manage to find those files? Im going on that journey now as well.

**Comment by dustinrc** [comment]
Using libcompose directly within my own code, I was experiencing the same issue. TLS certs were ruled out using curl:
```
$ curl --unix-socket /var/run/docker.sock http:/version
```
Explicitly setting `DOCKER_HOST=unix:///var/run/docker.sock` had a positive effect. Quickly searching, it seems the Darwin client [defaults](https://github.com/docker/libcompose/blob/e290a513ba909ca3afefd5cd611f3a3fe56f6a3a/vendor/github.com/docker/engine-api/client/client_darwin.go#L4) to a tcp port.

**Comment by dustinrc** [comment]
@kunalkushwaha @nickschuch, does setting `DOCKER_HOST` explicitly help in your case? @vdemeester, is this a change you would want to handle in libcompose, or would it be better to update the default in the upstream client?

**Comment by vdemeester** [comment]
@dustinrc hum good question… I think we should quickly handle it in `libcompose` for now, and discuss the default on the `engine-api` project :angel:

**Comment by kunalkushwaha** [comment]
@dustinrc Thanks, That fixes issue. 
I was trying to look for Cert files, but it is not required. My ``docker-machine`` had set ``DOCKER_TLS_VERIFY=1``, which is required to unset. 

@vdemeester I made a PR https://github.com/docker/engine-api/pull/342 in engine-api, as fixing in libcompose, required check for OS or repeat similar files for conditional compiling.
