### ISSUE TITLE
Missing an Exit Event to trigger when a container/service exits

### ISSUE THREAD

**Issue by dansteen** [docker/libcompose#282]
It looks like there is no "Exit" event that triggers when a container exits.   I do see a "Stop" and a "Kill" event, but those only trigger if the stop or kill action is taken on the container, not when the container exited by itself.  Am I missing something somewhere?

Thanks!

**Comment by vdemeester** [comment]
@dansteen yes, the events libcompose emits are related to libcompose objects (around services and projects). If you want container event, you need to subscribe to docker events. There is now the method `project.Event` that allow to do that on container for the current project (and the specified services if any).

But we might want to include some more events, maybe. /cc @joshwget

**Comment by joshwget** [comment]
If it'd be useful for someone I think adding more events would be fine. We don't have to necessarily use them in the events CLI command if we add events that Docker Compose doesn't show.

**Comment by dansteen** [comment]
My goal is to have a more "controlled" run of docker-compose, where each stage will wait for dependencies to be ready prior to moving on, and will also detect exits with "bad" exit codes.  This would allow easier incorporation into continuous integration tools (like jenkins).

**Comment by joshwget** [comment]
@dansteen I'd definitely be interested in chatting about this more. We use libcompose as part of our init system in RancherOS, so these types of features would be very useful for us (some of which we've already implemented). Note: I don't what or if any of this should end up in libcompose since we're striving to have compatibility with Docker Compose.

**Comment by dansteen** [comment]
@joshwget Sure! Basically, we are starting up a bunch of applications, some of which have dependencies.  We only want to start a dependent application after all of the applications it requires have started and/or run successfully.   Some applications will be services that need to run continuously, and some will be one-off commands that do some configuration or take some action or whatever and then exit.   So, as I see it, we need to check for the following things:

1.  Exit code (that it matches what we expect, or that it exits at all )
2.  Log file content (either a success message, or an error message)
3.  A timeout is exceeded.

In any of the above cases, if a process exits when it was supposed to keep running, or if it exits with the wrong exit value, or if a log file contains a message that indicates a failure, or if things take too long, we would discontinue the run, and exit the "controlled-compose" application with a failure code.  Otherwise, if specified, the application would wait for a specific message to show up in the logs for an application prior to continuing, and only continue starting up dependent applications when that message shows up.  That way we can be sure the prerequisite application is ready to accept requests prior to starting up the application that requires it.  
 
To accomplish the above, I would want to add a few additional configuration stanzas to the existing compose-file set.  Something like:

```
service:
  <name>:
      ...
      exit: <code>
      logmonitor:
          - file: <filename>
            regex:  <regex to search for>  
            state:  success | failure
      timeout: <value>
      ...
```

These stanzas could then be processed and pulled out (using the PreProcess function) prior to passing the config on to libcompose.  If they were missing for a specific application, then things would continue to work as they do now for that application.   

I think this would really add a lot of value.   I can certainly see how you would not want to include this in libcompose - but that's the joy of it being a library, it can be extended!

That's the basic idea, but I had a few other things I would want to support that aren't really directly related to this:

1. I love docker and docker-compose, but I have some dissatisfaction with how docker-compose handles dependent configuration.   Basically, as things stand, in a case where you have two applications with a docker-compose file for each,  and one of application requires the other, you need to include both files on the command line at the time that you run docker-compose.   This isn't particularly self-documenting as you will then need to document how you need to run docker-compose to successfully spin up the second application.  It would be great if there was a "requires" config stanza where you would put in a path to a docker-compose file that is required for this particular application to run.  That compose file would then be automatically read in when you run the compose application.
2.  docker-compose does, to my mind, some strange things with relative paths and current working directories, where it uses the path to the first config file as the "current working directory" for all functionality.   It will then create directories for exported volumes in the directory that the first config file on the command line lives in.  To me, it should always treat the working directory as the directory from which the compose application was run regardless of where the config files are located.   Ironically, the one exception to this would be the "requires" stanza mentioned above, which would treat all relative paths as being relative to the location of the config that mentions it rather than the directory that the "compose" application is run from.  

I've already written a script that does both of the above, but I would want to roll that into this code as well, since it seems like functionality that people might like.   It's not really related to controlling the composition per se, but I figured I would talk about it  :-) .

**Comment by dansteen** [comment]
As a note, I've got initial code that covers all of the above points here: https://github.com/dansteen/controlled-compose 

There is still a lot more to do, but it seems to work fairly well.   As a note, it does not look like the names of the services are picked up and added to the network "aliases" list (per the first paragraph here: https://docs.docker.com/compose/networking/).  Is there something special I need to do to configure that, or is it not just not yet implemented?

**Comment by vdemeester** [comment]
https://github.com/docker/libcompose/pull/294 :angel:

**Comment by dansteen** [comment]
Cool!  I'm going to close this issue since you guys added a way to get those events.  Thanks!
