### ISSUE TITLE
How do I call container operations

### ISSUE THREAD

**Issue by rajeevb2** [docker/libcompose#295]
With code below I can only call ID(), Name() and a couple of others. I would like to call all the methods in container.go (like Run, etc). How do I do that?

```
            service, err := pr.CreateService(name)
            conts, err := service.Containers()
            for _, cont := range conts {
                idstr, _ := cont.ID()
                fmt.Printf("Name %v %v\n", cont.Name(), idstr[:12])
            }

```

**Comment by vdemeester** [comment]
@rajeevb2 yeah for now you can't :sweat: However this will be possible at some point as `Container` and `Service` will be refactor a bunch (and thus we'll probably make a better/clearer `Container` interface).

**Comment by rajeevb2** [comment]
@vdemeester: I got it to work by changing project/service.go, docker/service.go, container/service.go. This is somewhat ugly, so I will wait for you to refactor :-)

**Comment by rajeevb2** [comment]
@vdemeester: I am going to close this since I was able to get past this but will wait for your refactor.
