### ISSUE TITLE
How do I order service calling and add delays as the services come up

### ISSUE THREAD

**Issue by rajeevb2** [docker/libcompose#299]
With docker-compose, I am able to bring up a complex site. With libcompose, the services are brought up too quickly and one of the apps (a legacy app) comes up ahead of the DB..

Is there a way to add delays between services and order the services as you up the project?

**Comment by joshwget** [comment]
Similar to Docker Compose, the `depends_on` key can be used to set a custom ordering for services being brought up. If you specify a link between your app and the database, that should also affect the order.

As for adding a delay between services, I don't think this is something that Docker Compose supports yet. If they do add it in the future, we'll be sure to add it!

**Comment by rajeevb2** [comment]
@joshwget Thanks. Here is my problem. I have a yml file that works on docker-compose and fails with libcompose. I originally thought the services were coming up too quickly and I put delays libcompose (by editing the code) and  it still fails. Now I am thinking the issue could be because of the "net:" attribute implementation. Is this implemented in libcompose?

**Comment by joshwget** [comment]
We do support the `net` key, so I think the issue is likely somewhere else. Would you mind posting the full Compose file?

**Comment by rajeevb2** [comment]
@joshwget, here is the compose file...If I bash into ofbiz container and do a "telnet localhost 1521", it works with docker-compose up and fails with "connection refused" with libcompose. I have this working on other apps that don't use the net key...

I don't have the latest libcompose -- do you know what parts of the code implement net key, I can check if they are the same?

oracle:
  privileged: true
  dns: []
  dns_search: []
  env_file: []
  image: oracle:dynamic
  ports:
  - 0.0.0.0:1521:1521
  - 0.0.0.0:7080:8080
  labels: {}
  links: []
ofbiz:
  net: "host"
  dns: []
  dns_search: []
  env_file: []
  environment:
  - OFBIZ_HOME=/opt/ofbiz
  image: ofbiz:dynamic
  command: /opt/ofbiz/start
  labels: {}
  ports:
  - 0.0.0.0:8080:8080
  - 0.0.0.0:8443:8443

**Comment by joshwget** [comment]
There was actually a brief period after v2 support landed when `net` was broken. Can you try again with the latest libcompose?

**Comment by rajeevb2** [comment]
@joshwget I am using 0.3.0-dev

**Comment by rajeevb2** [comment]
@joshwget it appears trunk version fixed the net issue. i had picked up a version on May 11 and this new version from June 10 appears to be a lot better. I suggest you bump up the version number. Also, I implemented an "Exec" feature like docker exec -it ... bash. I can send you the code or you can guide me on how to checkin. Might be a useful feature, even though docker-compose does not have this feature. Your call...

**Comment by joshwget** [comment]
`docker-compose exec` actually does exist! There's already an issue open for it (#211), so the contribution would definitely be welcome.

**Comment by rajeevb2** [comment]
@joshwget Should I send you a gist of changes? What is the best way to send the mods?
