### ISSUE TITLE
Add bundle command

### ISSUE THREAD

**Issue by vdemeester** [docker/libcompose#308]
A new `bundle` command appeared in `docker-compose` 1.8.0. Works with docker/docker#23522

```
    Generate a Docker bundle from the Compose file.
    Local images will be pushed to a Docker registry, and remote images
    will be pulled to fetch an image digest.
    Usage: bundle [options]
    Options:
        -o, --output PATH          Path to write the bundle file to.
                                   Defaults to "<project name>.dsb".
```

See docker/compose#3595

**Comment by joshwget** [comment]
I'm really curious to see where this feature is headed. There isn't much info/documentation available for it at the moment.

**Comment by cmingxu** [comment]
What's the ETA

**Comment by vdemeester** [comment]
@cmingxu giving the milestone I put in, end of august might be possible. Note that the support of `dab` file are in the `experimental` channel of docker, so the format might still change (in `docker/compose` and thus here too).

**Comment by cmingxu** [comment]
@vdemeester that would meet our project plan, looking forward to see it , thank you for your response.
