### ISSUE TITLE
networking config v2

### ISSUE THREAD

**Issue by dansteen** [docker/libcompose#319]
Hey!

Is there something specific that I need to do to get networking config to work in v2?  Using docker-compose, the following config will result in a "default" network config labled after the project name to be connected to the container started up:

```
version: '2'
services:
  org-api.app.local:
    image: org-api:testbob
```

Is there something more than just:

`APIProject.Up(context.Background(), options.Up{options.Create{ForceRecreate: true}}, service_name)`

needed?  Do I need to specifically create the networks?  I did not see anything relevant to this in the CLI code, and while I see a number of functions related to networking, it's not clear to me what I need to do with them.

**Comment by vdemeester** [comment]
@dansteen given the recent merge of the network v2 support merged, it should work with master yes :wink:. Tell me if it's not working :angel:

**Comment by dansteen** [comment]
@vdemeester thanks!  I've been keeping an eye on that one 😄 .  It does not seem to be creating any networks or network related items.   If it helps, the actual code I am using is here:  https://github.com/dansteen/controlled-compose/blob/master/cmd/up.go

**Comment by agerlic** [comment]
@vdemeester it seems libcompose doesn't create the default network like docker-compose : 
```
docker-compose up
Creating network "test_default" with the default driver
```

**Comment by vdemeester** [comment]
@agerlic hum weird, it should create the default network but it doesn't… marking this as a bug :sweat: It doesn't print the *"creation" print*, this is weird too :sweat_smile:. Gotta look into it :angel:

**Comment by elewis787** [comment]
Any update on this ? Just started playing with libcompose, but ill try to debug whats going on.
