### ISSUE TITLE
Is the LGPL license of the YAML library compatible?

### ISSUE THREAD

**Issue by nathanleclaire** [docker/libcompose#33]
I'm really not sure on this one but we probably should check with a legal team if we haven't already to make sure that vendoring / statically linking to the YAML parsing library, which is released under the LGPL license, is compatible with the overall project's Apache license.

**Comment by thaJeztah** [comment]
Good call, does this cover the use case here? http://stackoverflow.com/questions/1174240/apache-and-lgpl-license-compatibility 

(gosh, this licensing stuff is complex)

**Comment by ibuildthecloud** [comment]
Ugh call a lawyer.  Generally LGPL is fine when dynamically linked.  According to project

> The yaml package is licensed under the LGPL with an exception that allows it to be linked statically. Please see the LICENSE file for details.

Im guessing it's fine.  If it's not basically somebody wrote a go library that can never be used :(  But I know a lot of conservative people just avoid all GPL like the plague.

**Comment by joshwget** [comment]
We moved over to [candiedyaml](https://github.com/cloudfoundry-incubator/candiedyaml) (Apache) a while back to avoid this issue.
