### ISSUE TITLE
Consider moving docker/client.go to samalba/dockerclient

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/libcompose#36]
https://github.com/docker/libcompose/blob/14f3832526c37fc9a7557c6e677336299d822cee/docker/client.go

Looks like this file has no compose-specific stuff and other projects which will also talk to the docker daemon has to construct a `tls.Config` by duplicating the code in the `CreateClient` method. Moving this common functionality to `samalba/dockerclient` repo would make a lot of sense for users of that package, too.

**Comment by ibuildthecloud** [comment]
This sounds like a good idea.  Anybody like @samalba @vieux @aluzzardi @icecrime have any comments here?

**Comment by dnephin** [comment]
+1

**Comment by ibuildthecloud** [comment]
Honestly I'd like to switch to https://github.com/fsouza/go-dockerclient.  Not that that is in anyway related, but just saying :)

**Comment by ahmetalpbalkan** [comment]
@ibuildthecloud +1. A client independent of docker/docker is a healthier process.

**Comment by ibuildthecloud** [comment]
@ahmetalpbalkan I created https://github.com/docker/libcompose/issues/71 to discuss this.
