### ISSUE TITLE
for config `func parseLine()`, any reason we chose not to use os.ExpandEnv(string)

### ISSUE THREAD

**Issue by weitenghuang** [docker/libcompose#382]
I'm curious if we can simply use [`os.ExpandEnv(s string)`](https://golang.org/src/os/env.go?s=961:992#L22) for the same purpose in [`func parseLine()`](https://github.com/docker/libcompose/blob/master/config/interpolation.go#L80)?

**Comment by joshwget** [comment]
I remember there being some reason I couldn't use `os.ExpandEnv` when I was writing this. I'm pretty sure it related to how errors/warnings are handled, but I'd have to take a look at it again to be certain.

**Comment by weitenghuang** [comment]
@joshwget thanks, if you find out we can use `os.ExpandEnv`, i am happy to make the change and also help on #381

**Comment by weitenghuang** [comment]
after further review, it takes more changes and risk to use `os.Expand(string, mapping func (string) string)`, and not really adding additional values.
For example: when using `os.Expand()`, `$$variable` or `$${variable}` the second dollar sign will not be escaped (if mapping is `os.Getenv`, the result will be `variable`, or `{variable}`); hence, we will need to have another closure func to wrap our `mapping func` (`Lookup`), and manually escape those special characters. I asked this in Golang nuts, hope someone might give me feedback
https://groups.google.com/forum/#!topic/golang-nuts/F338qAlDbQQ
So I will close this question now, unless you have different opinion. Thank you for looking into it =)
