### ISSUE TITLE
unable to list services

### ISSUE THREAD

**Issue by geoffhendrey** [docker/libcompose#402]
I want to list the services in the yaml file. To do this, since I don't see a method capable of it in the APIProject, I must use config.Project as follows, but I get "imports github.com/docker/libcompose/config/: use of vendored package not allowed" when I try to access the config package:

```
func processComposeYml() {
    logger.SetDebug(true)
    apiProject, err := docker.NewProject(&ctx.Context{
        Context: project.Context{
            ComposeFiles: []string{"docker-compose.yml"},
            ProjectName:  "avanti-tmp",
        },
    }, nil)

    if err != nil {
        log.Fatal(err)
    }
    //must type assert to get to the underlying project.Project
    //since APIProject does not allow us to list all the services
    //in the YML file
    var proj *project.Project
    proj = apiProject.(*project.Project)

    for _, svcName := range proj.ServiceConfigs.Keys() {
        doSomethingWithService(apiProject.GetServiceConfig(svcName))
    }

}
```

**Comment by joshwget** [comment]
This code seems fine, so I think this is a pretty general Go issue. Are you sure your environment is setup properly? Is libcompose vendored properly (if you're vendoring)?

**Comment by geoffhendrey** [comment]
You are right. It was go vendor newbie stuff. Sorry for the bother.
