### ISSUE TITLE
Build segmentation fault in github.com/vbatts/tar-split when building 

### ISSUE THREAD

**Issue by james-nesbitt** [docker/libcompose#407]
When building as a library in another application, on Mac OSX (64) the following error occurs

```
    go build github.com/docker/libcompose/vendor/github.com/vbatts/tar-split/tar/storage: /usr/local/go/pkg/tool/darwin_amd64/compile: signal: segmentation fault
    fatal error: unexpected signal during runtime execution
    [signal 0xb code=0x1 addr=0xc04e1e3a37f pc=0x17cc60]
```

https://github.com/vbatts/tar-split/issues/37

**Comment by james-nesbitt** [comment]
solution seeems discovered in the upstream issue

**Comment by vbatts** [comment]
Seems it is related to the golang compiler version used on darwin.
https://github.com/vbatts/tar-split/issues/37#issuecomment-255763245

updating to `go1.7.3` fixed the issue.

**Comment by vbatts** [comment]
for the record, it would be good to update the vendored version of tar-split used by libcompose! there are some needed fixes.

**Comment by vdemeester** [comment]
@vbatts yes, will do 😇 thanks 😝

**Comment by vbatts** [comment]
:nerd_face:
