### ISSUE TITLE
libcompose fails when extends is string

### ISSUE THREAD

**Issue by surajssd** [docker/libcompose#428]
using this docker-compose file
```yaml
version: '2' 
services:
  foo:
    image: foo 

  bar:
    extends: foo
```

libcompose fails as:
```bash
$ libcompose up
WARN[0000] Note: This is an experimental alternate implementation of the Compose CLI (https://github.com/docker/compose) 
ERRO[0000] Could not parse config for project libcom : Service 'bar' has neither an image nor a build context specified. At least one must be provided. 
FATA[0000] Failed to read project: Service 'bar' has neither an image nor a build context specified. At least one must be provided. 
```

when using extends in following format, it works fine:

```yaml
version: '2' 
services:
  foo:
    image: foo 

  bar:
    extends:
      service: foo
```

libcompose worked fine:
```bash
$ libcompose up
WARN[0000] Note: This is an experimental alternate implementation of the Compose CLI (https://github.com/docker/compose) 
Creating network "libcom_default" with driver ""
INFO[0000] [0/2] [foo]: Starting                        
INFO[0000] [0/2] [bar]: Starting                        
Pulling foo (foo)...
<snip>
```

Ref: https://github.com/kubernetes-incubator/kompose/issues/357

**Comment by joshwget** [comment]
There's been a little bit of discussion around this already.

#185 
https://github.com/docker/compose/issues/3363

At this point it's probably best to just support this since Docker Compose seems to.

**Comment by surajssd** [comment]
>At this point it's probably best to just support this since Docker Compose seems to.

@joshwget sorry I didn't get this part? docker-compose supports extends to be string as service name in same file, string as name of some other file, object with filename and servicename?

So what part are you asking should be supported?

**Comment by joshwget** [comment]
Sorry, just saying that we should just mimic Docker Compose even if it's not confirmed that's how the feature was designed.

- If it's a string, treat it as a service in the same file
- If it's an object, use the existing behavior
