### ISSUE TITLE
.env file lookup in current directory rather than docker-compose file directory

### ISSUE THREAD

**Issue by surajnarwade** [docker/libcompose#443]
when I do from same directory where docker-compose file is placed, everything works fine
```
$ libcompose up
```
but, when I do from any other directory, like 
```
libcompose -f test/docker-compose.yml up
```
it fails, it looks for .env file in current directory rather than test.

**Comment by vdemeester** [comment]
For reference : https://github.com/docker/docker.github.io/blob/master/compose/compose-file/index.md#env_file 👼

**Comment by surajnarwade** [comment]
I want to work on it

**Comment by surajnarwade** [comment]
cc @vdemeester
