### ISSUE TITLE
Defining a service with both image: and build: is incorrectly not supported

### ISSUE THREAD

**Issue by rifelpet** [docker/libcompose#471]
Currently if a service has both `image:` and `build:`, the `build:` is [removed from the service's configuration](https://github.com/docker/libcompose/blob/3066e414fad534580ae31f760af98125c1b84293/config/merge.go#L227-L231). This conflicts with what [compose supports](https://github.com/docker/compose/pull/2458) (see also the [compose reference](https://docs.docker.com/compose/compose-file/compose-file-v2/#image)). Can those lines be removed so that services can be defined with both? I can open a PR if desired.

```
~> docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true

~> docker info
uname -a
Containers: 44
 Running: 2
 Paused: 0
 Stopped: 42
Images: 2072
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.27-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: QFKE:JB4V:4MRS:J5AM:WVZE:CHQK:X76Z:X3T3:EDML:D7YV:MYOJ:PW2O
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 32
 Goroutines: 47
 System Time: 2017-05-23T20:36:06.985221856Z
 EventsListeners: 2
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

~> uname -a
Darwin ho-mbp-1330.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
```

Repro:
* Use a docker-compose file with both build and image defined:
```
version: '2'
services:
  app:
    image: httpd
    build:
      context: .
```
* `project.GetServiceConfig("app")` returns a `config.ServiceConfig` whose `Build.Context` is an empty string. Removing `image: httpd` causes the `Build.Context` to then contain the correct context path.

**Comment by vdemeester** [comment]
@rifelpet oh.. I thought it was just calling `mergeConfig` on v1 compose files.. it seems it does the same for v2.. We should still have thoses lines around for v1 compose file (because `docker-compose` acts the same). Having `build` and `image` in the compose file is a v2 or above thing, so we should do the same. So those lines should only be executed on v1 compose files.
