### ISSUE TITLE
compose version: "2.0"

### ISSUE THREAD

**Issue by abuckenheimer** [docker/libcompose#490]
Hey folks, 

Noticed an [issue ](https://github.com/aws/amazon-ecs-cli/issues/305#issuecomment-327244778) using a downstream project [ecs-cli](https://github.com/aws/amazon-ecs-cli) where libcompose fails to parse the compose file when version is set to "2.0" instead of "2". I have never been a gopher but if I had to take a stab at it it seems like the issue is a naive string comparison [here](https://github.com/docker/libcompose/blob/aadc1f7ce5d373af10e7f841eefea8ca94a0548b/config/merge.go#L34): ``` if config.Version != "2" { ... ``` when really one would want to check for "2" or "2.0"?

A good test might be ```./libcompose-cli config | ./libcompose-cli -f - config``` using any docker-compose.yml. This is essentially how I ran into the bug in the wild and is a convenient way to assert that libcompose-cli config only outputs valid compose files and can read all valid compose files.

Thanks in advance! Sorry I can't be any more help :sad:

**Comment by CpuID** [comment]
This can be closed thanks to https://github.com/docker/libcompose/pull/507 for now I think (lack of test coverage, but the bug is resolved).
