### ISSUE TITLE
Lowercase sirupsen/logrus package import

### ISSUE THREAD

**Issue by rifelpet** [docker/libcompose#493]
I'm using libcompose and need a more recent version of `docker/docker` than what is pinned in libcompose's `vendor.conf`. One of the issues with using the latest master branch of `docker/docker` is that it imports a lowercase `sirupsen/logrus` while libcompose imports `Sirupsen/logrus`.

I went through libcompose's imports and the only ones using Logrus import the lowercase version in their master branch.

Can libcompose be switched to use the lowercase import and have its dependencies be updated to more recent versions?

**Comment by vdemeester** [comment]
yes, I was waiting for docker/docker and docker/cli to get updated

**Comment by arbourd** [comment]
Related PR: #498

**Comment by rifelpet** [comment]
Closed via #498
