### ISSUE TITLE
go get fails

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/libcompose#52]
I'm not sure how to correctly vendor this repo:

```
➜ mkdir gopath-example
➜ cd gopath-example
➜ export GOPATH=`pwd`
➜ go get -d github.com/docker/libcompose/docker
package github.com/docker/docker/autogen/dockerversion: cannot find package "github.com/docker/docker/autogen/dockerversion" in any of:
	/usr/local/Cellar/go/1.5/libexec/src/github.com/docker/docker/autogen/dockerversion (from $GOROOT)
	/Users/alp/workspace/gopath-example/src/github.com/docker/docker/autogen/dockerversion
```

I can see the pkg is here https://github.com/docker/libcompose/tree/master/Godeps/_workspace/src/github.com/docker/docker/autogen/dockerversion but not sure why it is hitting github for the dependencies.

Sorry in advance if it's some obvious thing about godeps but it seemed like this should be working.

**Comment by ibuildthecloud** [comment]
This is basically a dup of https://github.com/docker/libcompose/issues/32

**Comment by ahmetalpbalkan** [comment]
Fair point.
