### ISSUE TITLE
Jenkins marking tests successful when they fail?

### ISSUE THREAD

**Issue by CpuID** [docker/libcompose#527]
https://jenkins.dockerproject.org/job/docker/job/libcompose/branch/master/178/consoleFull

Ctrl+f `failed`, whereas the build supposedly is passing?

This GH issue should be about ensuring Jenkins reflects reality, not necessarily fixing the underlying tests.

**Comment by CpuID** [comment]
```
13:12:12 =============== 79 failed, 43 passed, 1 error in 654.69 seconds ================
```

**Comment by vdemeester** [comment]
@CpuID yes, the acceptance tests from `docker/compose` are here for information (of what was required for the library to do), but they are not bloking

**Comment by CpuID** [comment]
Fair enough, I'll close this in that case.
