### ISSUE TITLE
Propose using https://github.com/fsouza/go-dockerclient

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/libcompose#71]
We currently use https://github.com/samalba/dockerclient to talk to Docker.  I propose we switch to https://github.com/fsouza/go-dockerclient.  The advantage of https://github.com/fsouza/go-dockerclient is that it has full coverage of the Docker API and is written in a style that is forward compatible.  The @fsouza client seems more active from a larger community perspective where as the samalba client is largely contributed and maintained by maintainers of other Docker projects.  While samalba client is used in other projects like swarm (and machine?) the usage of the Docker API seems to be quite a small subset.  Furthermore I've found @fsouza to be very responsive to merging PRs where as the samalba client does seem to take much longer.

**Comment by ahmetalpbalkan** [comment]
:+1:

**Comment by imikushin** [comment]
:+1:  for fsouza/go-dockerclient

**Comment by dnephin** [comment]
It does seem to be a more active project. Works for me.

**Comment by vdemeester** [comment]
Works for me too 🐶.

**Comment by ibuildthecloud** [comment]
Fixed in #78
