### ISSUE TITLE
`make all` doesn't do "all"

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/libcompose#75]
I'm not sure how the build system and Jenkins is setup, so I don't fully understand the Makefile setup.  Currently `make all` just does a build and not run tests.  I keep forgetting to run `test` or `validate` before I check in, resulting in failed builds on Jenkins.

Is there a simple target I can run that will run all tests and validation basically simulating what Jenkins would do?

@vdemeester

**Comment by vdemeester** [comment]
@ibuildthecloud currently not, but I'll submit a PR right away :wink:
