### ISSUE TITLE
Switch to non-LGPL yaml parser

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/libcompose#79]
https://github.com/go-yaml/yaml is licensed under [LGPL with exceptions](https://github.com/go-yaml/yaml#license).  While legally it is probably okay to run this software many organizations have a strict no GPL of any kind allowed policy for libraries.  I think it is worthwhile investigating alternative yaml libraries.  One possible library is https://github.com/cloudfoundry-incubator/candiedyaml.

**Comment by xiaods** [comment]
+1

**Comment by ibuildthecloud** [comment]
We are going to give this a shot.

ping @imikushin

**Comment by imikushin** [comment]
@ibuildthecloud I'll see what I can do.
