### ISSUE TITLE
Error when referring to libcompose as a dependency

### ISSUE THREAD

**Issue by gondor** [docker/libcompose#84]
I am currently integrating libcompose as a dependency in my project and am getting the following error.

Importing:
```
import (
	"github.com/docker/libcompose/docker"
	"github.com/docker/libcompose/project"
)
```

Updating dependencies via go get:
```
go get ./...
```

Error:
```
package github.com/docker/docker/autogen/dockerversion: cannot find package "github.com/docker/docker/autogen/dockerversion" in any of:
	/usr/local/Cellar/go/1.5.1/libexec/src/github.com/docker/docker/autogen/dockerversion (from $GOROOT)
	/Users/junruh/Development/golang/src/github.com/docker/docker/autogen/dockerversion (from $GOPATH)
```

I get the same issues using the example within the README.  Any suggestions on how to get around this?

**Comment by gondor** [comment]
Sorry, just found issue #32 . If it appears it will address this issue then you can close this

**Comment by vdemeester** [comment]
@gondor thank you :wink: It's something we're trying to address, hopefully should be done in not too much time :stuck_out_tongue_closed_eyes:
