### ISSUE TITLE
Support multiple -f

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/libcompose#98]
https://github.com/docker/compose/blob/129092b7/docs/reference/docker-compose.md

**Comment by ehaydenr** [comment]
It seems like type `Context` in project/context could be changed such that `ComposeFile` changes from `string` to `[]string` or upon parsing the flags, a temporary yml could be created from the concatenation of each file specified. It seems like the latter might be cleaner.

**Comment by dsvmacdonald** [comment]
Any idea when this will be fixed?  I see a PR that looks promising.
